//PRODUCTS
export const  GET_PRODUCTS = 'GET_PRODUCTS'
export const  LOAD_PRODUCTS = 'LOAD_PRODUCTS'
//CART
export const  ADD_TO_CART = 'ADD_TO_CART'
export const  REMOVE_FROM_CART = 'REMOVE_FROM_CART'

//ANY EVENT POPUP
export const  SHOW_POPUP = 'SHOW_POPUP'
export const  HIDE_POPUP = 'HIDE_POPUP'


//USER INFO ORDER
export const  SET_VALUE = 'SET_VALUE'
export const  CHECK_VALIDITY_FORM = 'CHECK_VALIDITY_FORM'

//RESULT TYPES
export const  ERROR = 'ERROR'
export const  SUCCESS = 'SUCCESS'

//NEW ORDER
export const  SEND_ORDER = 'SEND_ORDER'
export const  SENDING_ORDER = 'SENDING_ORDER'
export const  ORDER_SENT = 'ORDER_SENT'
export const  ORDER_ERROR = 'ORDER_ERROR'

//FETCH ORDER
export const  FETCH_ORDER = 'FETCH_ORDER'
export const  LOAD_ORDER = 'LOAD_ORDER'
export const  LOADING_ORDER = 'LOADING_ORDER'
export const  ERROR_LOADING_ORDER = 'ERROR_LOADING_ORDER'
export const  RESET_ORDER = 'RESET_ORDER'

